version: '2.13.0'
services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: Loner123
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
